import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Button } from "@/components/ui/button";
import Image from "next/image";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TooltipProvider>
      <html lang="en" className={cn("font-sans", geist.variable)}>
        <body
          className={`${inter.className} antialiased`}
          suppressHydrationWarning
        >
          <SidebarProvider>
            <AppSidebar className="border-r border-transparent" />
            <SidebarInset className="relative">
              {children}

              <Button
                size="icon-lg"
                className="rounded-full absolute z-20 right-6 bottom-12 size-14"
                style={{
                  background: "hsla(240, 4%, 10%, 1)",
                  boxShadow:
                    "0px 1px 2px 0px hsla(0, 0%, 0%, 0.05) 0px -1px 0px 0px hsla(0, 0%, 0%, 0.1) inset",
                }}
              >
                <Image
                  src="/assets/Vector.png"
                  alt="message icon"
                  width={26.67}
                  height={26.67}
                />
              </Button>
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </TooltipProvider>
  );
}
